spring:
  application:
    name: dms
  datasource:
    url: jdbc:postgresql://localhost:5432/document_db
    username: db_user
    password: db_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true